all:
	(cd lib;$(MAKE))
	(cd mochiweb;$(MAKE))
	(cd mbrella;$(MAKE))
	(cd pipeline;$(MAKE))

lib:
	(cd lib;$(MAKE))
	
pipeline:
	(cd pipeline;$(MAKE))

mochiweb:
	(cd mochiweb;$(MAKE))
	
mbrella:
	(cd mbrella;$(MAKE))